server:
  port: 9527



eureka:
  client:
    service-url:
      defaultZone: http://eurakeserver9000.com:9000/eureka
  instance:
    instance-id: zhifubao_9527
    prefer-ip-address: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: zhifubao   #当前服务的名字，后面会用到