server:
  port: 9527

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eurakeserver9000.com:9000/eureka
#  instance:
#    instance-id: zhifubao_8866
#    prefer-ip-address: true