server:
  port: 8888    #当前服务的端口号

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
     # defaultZone: http://eurakeserver9000.com:9000/eureka,http://eurakeserver9001.com:9001/eureka,http://eurakeserver9002.com:9002/eureka
      defaultZone:  http://eurakeserver9000.com:9000/eureka
  instance:
    instance-id: comment_provider_8888 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址

spring:
  application:
    name: comment_provider_8888   #当前服务的名字，后面会用到
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://120.79.100.105:3306/youfinema              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                      # 数据库连接池的最小维持连接数
      initial-size: 5                                  # 初始化连接数
      max-total: 5                                     # 最大连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间