server:
  port: 9527



eureka:
  client:
    service-url:
      defaultZone: http://eurakeserver9000.com:9000/eureka
  instance:
    instance-id: zhifubao_9527
    prefer-ip-address: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: zhifubao   #当前服务的名字，后面会用到
  #redis
  redis:
    database: 0         #连接Redis的库
    host: 192.168.3.135     #主机名称
    port: 6379          # 端口号
    password:           # 连接密码，没有密码可以不写
    lettuce:            # 設置redis連接池
       pool: 
         max-active: 10   # 最大連接數量
         max-wait: -1     # 連接等待時間，如果為-1 默認不等待
         max-idle: 8
         min-idle: 0      # 最小連接數量   
         timeout: 10000