server:
  port: 9001          #当前服务的端口号
  
spring:
   application:
    name: YouFCinema-zuul   #当前服务的名字，后面会用到
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eurakeserver9000.com:9000/eureka/
  instance: 
    instance-id: YouFCinema-zuul-9001 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  

# 路由的配置
zuul: 
  #ignored-services: woniucloud-provider    #设置不暴露微服务的名称
  ignored-services: "*"    # "*"的意思代表所有的微服务都将名字隐藏起来
  routes:
    product: #路由的名称，这个名字可以自己写
      service-id: YouFCinema-Order01
      path: /**      # 如果通过路由来访问，可以根据微服务的名字来访问，也可以直接访问资源
    film: 
      service-id: youfciname-film
      path: /**
    order: 
      service-id: YouFCinema-order02
      path: /**    
    comment: 
      service-id: comment-provider-8888
      path: /**    
    user: 
      service-id: user8247
      path: /**    
    
     
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


info: #监控信息 
  app.name: YouFCinema
  company.name: www.woniuxy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$