server:
  port: 9955      #当前服务的端口号
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.cinema.pojo             # 所有Entity别名类所在包
 # mapper-locations: classpath:mybatis/mapper/*.xml    # mapper映射文件

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eurakeserver9000.com:9000/eureka
  instance: 
    instance-id: YouFCinema-order9955 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址
    
spring:
   application:
    name: YouFCinema-order02   #当前服务的名字，后面会用到
   datasource:
    #type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://120.79.100.105:3306/youfinema?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true              # 数据库名称
    username: root
    password: 123456
   # dbcp2:
    #  min-idle: 5                                      # 数据库连接池的最小维持连接数
    #  initial-size: 5                                  # 初始化连接数
    #  max-total: 5                                     # 最大连接数
    #  max-wait-millis: 200                             # 等待连接获取的最大超时时间
    # redis的配置信息
   redis:
    database: 0         #连接Redis的库
    host: 192.168.3.135     #主机名称
    port: 6379          # 端口号
    password:           # 连接密码，没有密码可以不写
    lettuce:            # 設置redis連接池
       pool: 
         max-active: 10   # 最大連接數量
         max-wait: -1     # 連接等待時間，如果為-1 默認不等待
         max-idle: 8
         min-idle: 0      # 最小連接數量   
         timeout: 10000
    