server:
  port: 8247

spring:
  datasource:
    url: jdbc:mysql://120.79.100.105:3306/youfinema?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: user8247


eureka:
  client:
    service-url:
      defaultZone: http://eurakeserver9000.com:9000/eureka
  instance:
    instance-id: user8247
    prefer-ip-address: true