server:
  port: 9955      #当前服务的端口号
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.cinema.pojo             # 所有Entity别名类所在包
 # mapper-locations: classpath:mybatis/mapper/*.xml    # mapper映射文件

    
spring:
  # application:
    #name: woniucloud-provider   #当前服务的名字，后面会用到
   datasource:
    #type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://120.79.100.105:3306/youfinema?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true              # 数据库名称
    username: root
    password: 123456
   # dbcp2:
    #  min-idle: 5                                      # 数据库连接池的最小维持连接数
    #  initial-size: 5                                  # 初始化连接数
    #  max-total: 5                                     # 最大连接数
    #  max-wait-millis: 200                             # 等待连接获取的最大超时时间
      
    